server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://smartprintproject-hothanhnha25062004-0ace.h.aivencloud.com:19349/defaultdb?ssl-mode=REQUIRED"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: avnadmin
    password: /****inboxThanhNha/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "/OMSdnoPis5/iOGhhaYJcZYJZVg/GGyBNwFY7roCuir6AnYbG4PnRioUoBdgUmSC"
  valid-duration: 3600 # second
  refreshable-duration: 360000 # second
